package com.mazetar.mazLearnedThis.client.model;

//Date: 05.05.2013 20:46:08
//Template version 1.1
//Java generated by Techne
//Keep in mind that you still need to fill in some blanks
//- ZeuX

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelEntityMaz extends ModelBase {
    // fields
    ModelRenderer Head;
    ModelRenderer Headwear;
    ModelRenderer Body;
    ModelRenderer RightArm;
    ModelRenderer LeftArm;
    ModelRenderer RightLeg;
    ModelRenderer LeftLeg;

    public ModelEntityMaz() {
        textureWidth = 64;
        textureHeight = 32;
        

        Head = new ModelRenderer(this, 0, 0);
        Headwear = new ModelRenderer(this, 0, 16);
        Body = new ModelRenderer(this, 32, 16);
        RightArm = new ModelRenderer(this, 56, 0);
        LeftArm = new ModelRenderer(this, 56, 0);
        RightLeg = new ModelRenderer(this, 56, 0);
        LeftLeg = new ModelRenderer(this, 56, 0);

        Head.addBox(-4F, -8F, -4F, 8, 8, 8);
        Head.setRotationPoint(0F, -14F, 0F);
        Head.setTextureSize(64, 32);
        Head.mirror = true;
        setRotation(Head, 0F, 0F, 0F);
        
        Headwear.addBox(-4F, -8F, -4F, 8, 8, 8);
        Headwear.setRotationPoint(0F, -14F, 0F);
        Headwear.setTextureSize(64, 32);
        Headwear.mirror = true;
        setRotation(Headwear, 0F, 0F, 0F);
        
        Body.addBox(-4F, 0F, -2F, 8, 12, 4);
        Body.setRotationPoint(0F, -14F, 0F);
        Body.setTextureSize(64, 32);
        Body.mirror = true;
        setRotation(Body, 0F, 0F, 0F);

        RightArm.addBox(-1F, -2F, -1F, 2, 30, 2);
        RightArm.setRotationPoint(-5F, -12F, 0F);
        RightArm.setTextureSize(64, 32);
        RightArm.mirror = true;
        setRotation(RightArm, 0F, 0F, 0F);
        
        
        LeftArm.addBox(-1F, -2F, -1F, 2, 30, 2);
        LeftArm.setRotationPoint(5F, -12F, 0F);
        LeftArm.setTextureSize(64, 32);
        LeftArm.mirror = true;
        setRotation(LeftArm, 0F, 0F, 0F);
        
        RightLeg.addBox(-1F, 0F, -1F, 2, 30, 2);
        RightLeg.setRotationPoint(-2F, -2F, 0F);
        RightLeg.setTextureSize(64, 32);
        RightLeg.mirror = true;
        setRotation(RightLeg, 0F, 0F, 0F);
        
        
        LeftLeg.addBox(-1F, 0F, -1F, 2, 30, 2);
        LeftLeg.setRotationPoint(2F, -2F, 0F);
        LeftLeg.setTextureSize(64, 32);
        LeftLeg.mirror = true;
        setRotation(LeftLeg, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3,
            float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Head.render(f5);
        Headwear.render(f5);
        Body.render(f5);
        RightArm.render(f5);
        LeftArm.render(f5);
        RightLeg.render(f5);
        LeftLeg.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float par1, float par2, float par3,
            float par4, float par5, float par6, Entity par7Entity) {
        super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
    }

}
